CREATE TABLE SELLER(
    SELLER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50)
);

CREATE TABLE INVOICE(
    INVOICE_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    SELLER_ID VARCHAR(50) NOT NULL,
    AMOUNT NUMERIC(10, 2) NOT NULL,
    CONSTRAINT "FK_INVOICE_SELLER" FOREIGN KEY (SELLER_ID) REFERENCES SELLER (SELLER_ID)
);

INSERT INTO SELLER(SELLER_ID, NAME) VALUES('1', 'jose da Silva');
INSERT INTO SELLER(SELLER_ID, NAME) VALUES('2', 'Maria Souza');

INSERT INTO INVOICE(INVOICE_ID, SELLER_ID, AMOUNT) VALUES('101', '1', 50.00);
INSERT INTO INVOICE(INVOICE_ID, SELLER_ID, AMOUNT) VALUES('102', '1', 100.00);
INSERT INTO INVOICE(INVOICE_ID, SELLER_ID, AMOUNT) VALUES('103', '1', 150.00);
INSERT INTO INVOICE(INVOICE_ID, SELLER_ID, AMOUNT) VALUES('104', '1', 200.00);

INSERT INTO INVOICE(INVOICE_ID, SELLER_ID, AMOUNT) VALUES('201', '2', 10.00);
INSERT INTO INVOICE(INVOICE_ID, SELLER_ID, AMOUNT) VALUES('202', '2', 20.00);
INSERT INTO INVOICE(INVOICE_ID, SELLER_ID, AMOUNT) VALUES('203', '2', 30.00);
INSERT INTO INVOICE(INVOICE_ID, SELLER_ID, AMOUNT) VALUES('204', '2', 40.00);
