server:
  port: 8080

spring:
  application:
    name: dasafio-san-giorgio
  datasource:
    password: docker
    username: docker
    url: jdbc:postgresql://localhost:5432/desafio
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka-topics:
  over-payment: over-payment-topic
  full-payment: full-payment-topic
  partial-payment: partial-paymenttopic

logging:
  level:
    root: info

